"""Constants used in the project."""

LANGUAGE_MAPPING = {
    # ISO 639-1 language codes
    "ab": "Abkhazian",
    "aa": "Afar",
    "af": "Afrikaans",
    "sq": "Albanian",
    "am": "Amharic",
    "ar": "Arabic",
    "an": "Aragonese",
    "hy": "Armenian",
    "as": "Assamese",
    "av": "Avaric",
    "ae": "Avestan",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "bm": "Bambara",
    "ba": "Bashkir",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bi": "Bislama",
    "bs": "Bosnian",
    "br": "Breton",
    "bg": "Bulgarian",
    "my": "Burmese",
    "ca": "Catalan",
    "ch": "Chamorro",
    "ce": "Chechen",
    "ny": "Chichewa",
    "zh-cn": "Simplified Chinese",
    "zh-tw": "Traditional Chinese",
    "cu": "Church Slavic",
    "cv": "Chuvash",
    "kw": "Cornish",
    "co": "Corsican",
    "cr": "Cree",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "dv": "Divehi",
    "dz": "Dzongkha",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "ee": "Ewe",
    "fo": "Faroese",
    "fj": "Fijian",
    "fi": "Finnish",
    "fr": "French",
    "fy": "Western Frisian",
    "ff": "Fulah",
    "gd": "Gaelic",
    "gl": "Galician",
    "lg": "Ganda",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "kl": "Greenlandic",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian",
    "ha": "Hausa",
    "he": "Hebrew",
    "hz": "Herero",
    "hi": "Hindi",
    "ho": "Hiri Motu",
    "hu": "Hungarian",
    "is": "Icelandic",
    "io": "Ido",
    "ig": "Igbo",
    "id": "Indonesian",
    "ia": "Interlingua",
    "ie": "Interlingue",
    "iu": "Inuktitut",
    "ik": "Inupiaq",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "kn": "Kannada",
    "kr": "Kanuri",
    "ks": "Kashmiri",
    "kk": "Kazakh",
    "km": "Central Khmer",
    "ki": "Kikuyu",
    "rw": "Kinyarwanda",
    "ky": "Kirghiz",
    "kv": "Komi",
    "kg": "Kongo",
    "ko": "Korean",
    "kj": "Kuanyama",
    "ku": "Kurdish",
    "lo": "Lao",
    "la": "Latin",
    "lv": "Latvian",
    "li": "Limburgan",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lu": "Luba-Katanga",
    "lb": "Luxembourgish",
    "mk": "Macedonian",
    "mg": "Malagasy",
    "ms": "Malay",
    "ml": "Malayalam",
    "mt": "Maltese",
    "gv": "Manx",
    "mi": "Maori",
    "mr": "Marathi",
    "mh": "Marshallese",
    "mn": "Mongolian",
    "na": "Nauru",
    "nv": "Navajo",
    "nd": "Northern Ndebele",
    "nr": "South Ndebele",
    "ng": "Ndonga",
    "ne": "Nepali",
    "no": "Norwegian",
    "nb": "Norwegian Bokmål",
    "nn": "Norwegian Nynorsk",
    "ii": "Sichuan Yi",
    "oc": "Occitan",
    "oj": "Ojibwa",
    "or": "Oriya",
    "om": "Oromo",
    "os": "Ossetian",
    "pi": "Pali",
    "ps": "Pashto",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "pa": "Punjabi",
    "qu": "Quechua",
    "ro": "Romanian",
    "rm": "Romansh",
    "rn": "Rundi",
    "ru": "Russian",
    "se": "Northern Sami",
    "sm": "Samoan",
    "sg": "Sango",
    "sa": "Sanskrit",
    "sc": "Sardinian",
    "sr": "Serbian",
    "sn": "Shona",
    "sd": "Sindhi",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "st": "Sotho",
    "es": "Spanish",
    "su": "Sundanese",
    "sw": "Swahili",
    "ss": "Swati",
    "sv": "Swedish",
    "tl": "Tagalog",
    "ty": "Tahitian",
    "tg": "Tajik",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "th": "Thai",
    "bo": "Tibetan",
    "ti": "Tigrinya",
    "to": "Tonga",
    "ts": "Tsonga",
    "tn": "Tswana",
    "tr": "Turkish",
    "tk": "Turkmen",
    "tw": "Twi",
    "ug": "Uighur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "ve": "Venda",
    "vi": "Vietnamese",
    "vo": "Volapük",
    "wa": "Walloon",
    "cy": "Welsh",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "za": "Zhuang",
    "zu": "Zulu",
    # Additional languages in ISO 639-3 format
    "ace": "Achinese",
    "ady": "Adyghe",
    "als": "Tosk Albanian",
    "alt": "Southern Altai",
    "ami": "Amis",
    "ang": "Old English",
    "anp": "Angika",
    "arc": "Aramaic",
    "ary": "Moroccan Arabic",
    "arz": "Egyptian Arabic",
    "ast": "Asturian",
    "atj": "Atikamekw",
    "avk": "Kotava",
    "awa": "Awadhi",
    "azb": "South Azerbaijani",
    "ban": "Balinese",
    "bar": "Bavarian",
    "bcl": "Bikol Central",
    "bjn": "Banjar",
    "blk": "Pa'O",
    "bpy": "Bishnupriya",
    "bug": "Buginese",
    "bxr": "Russia Buriat",
    "cdo": "Min Dong Chinese",
    "ceb": "Cebuano",
    "chr": "Cherokee",
    "chy": "Cheyenne",
    "ckb": "Central Kurdish",
    "crh": "Crimean Tatar",
    "csb": "Kashubian",
    "dag": "Dagbani",
    "din": "Dinka",
    "diq": "Dimli",
    "dsb": "Lower Sorbian",
    "dty": "Dotyali",
    "ext": "Extremaduran",
    "fat": "Fanti",
    "fon": "Fon",
    "frp": "Arpitan",
    "frr": "Northern Frisian",
    "fur": "Friulian",
    "gag": "Gagauz",
    "gan": "Gan Chinese",
    "gcr": "Guianese Creole French",
    "glk": "Gilaki",
    "gom": "Goan Konkani",
    "gor": "Gorontalo",
    "got": "Gothic",
    "gpe": "Ghanaian Pidgin English",
    "guc": "Wayuu",
    "gur": "Farefare",
    "guw": "Gun",
    "hak": "Hakka Chinese",
    "haw": "Hawaiian",
    "hif": "Fiji Hindi",
    "hsb": "Upper Sorbian",
    "hyw": "Western Armenian",
    "ilo": "Iloko",
    "inh": "Ingush",
    "jam": "Jamaican Creole English",
    "jbo": "Lojban",
    "kaa": "Kara-Kalpak",
    "kab": "Kabyle",
    "kbd": "Kabardian",
    "kbp": "Kabiyè",
    "kcg": "Tyap",
    "koi": "Komi-Permyak",
    "krc": "Karachay-Balkar",
    "ksh": "Kölsch",
    "lad": "Ladino",
    "lbe": "Lak",
    "lez": "Lezghian",
    "lfn": "Lingua Franca Nova",
    "lij": "Ligurian",
    "lld": "Ladin",
    "lmo": "Lombard",
    "ltg": "Latgalian",
    "mad": "Madurese",
    "mai": "Maithili",
    "mdf": "Moksha",
    "mhr": "Eastern Mari",
    "min": "Minangkabau",
    "mni": "Manipuri",
    "mnw": "Mon",
    "mrj": "Western Mari",
    "mwl": "Mirandese",
    "myv": "Erzya",
    "mzn": "Mazanderani",
    "nap": "Neapolitan",
    "nds": "Low German",
    "nds-nl": "Low Saxon",
    "new": "Newari",
    "nia": "Nias",
    "nov": "Novial",
    "nqo": "N'Ko",
    "nrm": "Narom",
    "nso": "Northern Sotho",
    "olo": "Livvi",
    "pag": "Pangasinan",
    "pam": "Pampanga",
    "pap": "Papiamento",
    "pcd": "Picard",
    "pcm": "Nigerian Pidgin",
    "pdc": "Pennsylvania German",
    "pfl": "Pfaelzisch",
    "pih": "Pitcairn-Norfolk",
    "pms": "Piemontese",
    "pnb": "Western Panjabi",
    "pnt": "Pontic",
    "pwn": "Paiwan",
    "rmy": "Vlax Romani",
    "rue": "Rusyn",
    "sah": "Yakut",
    "sat": "Santali",
    "scn": "Sicilian",
    "sco": "Scots",
    "shi": "Tachelhit",
    "shn": "Shan",
    "skr": "Saraiki",
    "smn": "Inari Sami",
    "srn": "Sranan Tongo",
    "stq": "Saterfriesisch",
    "szl": "Silesian",
    "szy": "Sakizaya",
    "tay": "Atayal",
    "tcy": "Tulu",
    "tet": "Tetum",
    "tly": "Talysh",
    "tpi": "Tok Pisin",
    "trv": "Taroko",
    "tum": "Tumbuka",
    "tyv": "Tuvinian",
    "udm": "Udmurt",
    "vec": "Venetian",
    "vep": "Veps",
    "vls": "Vlaams",
    "war": "Waray",
    "wuu": "Wu Chinese",
    "xal": "Kalmyk",
    "xmf": "Mingrelian",
    "zea": "Zeeuws",
}
